markdown: kramdown
form_api_token: 66fa7ae6513b362f8766e006062c0881
navigation:
 - title: Productions
   url: /contenu/production.html
 - title: Plateforme
   url: /contenu/plateforme.html
 - title: Projets
   url: /contenu/projet.html
navigation-en:
 - title: Productions
   url: /content/production.html
 - title: Platform
   url: /content/platform.html
 - title: Projects
   url: /content/project.html
